# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:37017/ibm

---

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ibm
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  
show-sql: true 